package mainGame;

public enum ID {
	Player,
	Player2, // used for the other player in multiplayer
	Trail,
	BossEye,
	BullBoss,
	CircleTrail,
	EnemyFast,
	EnemySmart,
	EnemyBoss,
	EnemyBossBullet,
	EnemyBurst,
	EnemyBurstWarning,
	EnemySweep,
	EnemyShooter,
	EnemyShooterBullet,
	Firework,
	FireworkSpark,
	Levels1to10Text,
	EnemyBasic, 
	EnemyTracker,
	EnemyExpand,
	EnemyMiniShooter,
	EnemyMiniShooterBullet,
	EnemyPorcupine,
	PickupDoublePoints,
	PickupHealth,
	PickupNuke,
	PickupSpeed,
	PickupScore,
	PickupShrink,
	SurvivalText,
	RollBoss1,
	RollBoss2,
	EnemyMove, 
	SeparateBoss, 
	SeparateBoss2,
	SeparateBoss3,
	FireballAttack;
}
